spring.application.name=jwt-spring-security-02

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_db
spring.datasource.username=jwt_user
spring.datasource.password=jwt_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Swagger
# Remover customizações para usar os padrões
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html

# Outras configs
server.error.include-message=always

# Email
#spring.mail.host=${SPRING_MAIL_HOST}
#spring.mail.port=${SPRING_MAIL_PORT}
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
#spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meuemailteste.desenvolvimento@gmail.com
spring.mail.password=qrmcsulayrsyfrru
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logs
com.mvbr.jwtspringsecurity02=INFO
logging.level.org.springframework.security=TRACE
